### ISSUE TITLE
Player ID copied from highest index when registering ships in global scope

### ISSUE THREAD

**Issue by GeoffWilkinson** [Novaras/modkit#18]
When ships of the same type but on separate teams are "hoisted" in `modkit_hoist_memgroups()`, the step of registering the ship again has an unintended side effect.

In some custom code, running under `update()`, I do this to debug:

```
    print("------------------------------------------------------------------------------------")
    print("self.id: " .. self.id);
    print("self.player.id: " .. self.player.id);
    print("self.own_group: " .. self.own_group);
    print("SobGroup_GetPlayerOwner(self.own_group): " .. SobGroup_GetPlayerOwner(self.own_group));
    print("------------------------------------------------------------------------------------")
```

When the game first starts and before any attempt to hoist memgroups has happened (so pre tick 5) I get the following output:

```
------------------------------------------------------------------------------------
self.id: 16
self.player.id: 0
self.own_group: my_test_ship-16
SobGroup_GetPlayerOwner(self.own_group): 0
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
self.id: 384
self.player.id: 1
self.own_group: my_test_ship-384
SobGroup_GetPlayerOwner(self.own_group): 1
------------------------------------------------------------------------------------
```

When tick 5 comes around, modkit's logging in `modkit_hoist_memgroups()` gives:

```
[6.000004768371582] HOISTING GROUPS...
no ship matched, hoisting ship 384
no ship matched, hoisting ship 16
"table: 13A22520": {
        "384": {
                "group": "my_test_ship-384",
                "player": 1,
                "id": 384,
                "type": "my_test_ship",

        },
        "16": {
                "group": "my_test_ship-16",
                "player": 0,
                "id": 16,
                "type": "my_test_ship",
        },
},
```

This looks fine, the player IDs are still as expected, however...

The next part of my logging in custom code shows:

```
------------------------------------------------------------------------------------
self.id: 16
self.player.id: 1
self.own_group: my_test_ship-16
SobGroup_GetPlayerOwner(self.own_group): 1
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
self.id: 384
self.player.id: 1
self.own_group: my_test_ship-384
SobGroup_GetPlayerOwner(self.own_group): 1
------------------------------------------------------------------------------------
```

So `GLOBAL_SHIPS` has the correct data ( ship ID 16 - player 0, ship ID 384 - player 1) but for whatever reason, the reference to self in the prototype in the custom code is pointing at player 1 for both ships!

The core engine stuff works as normal but for the purpose of custom code, performing operations on the sobgroup as given by `self.own_group` or using the ship's player sub-table in functions such as `alliedWith` in this way give an incorrect result.

**Comment by Novaras** [comment]
Can you show the output from `modkit_hoist_memgroups.lua`?

>  the reference to self in the prototype in the custom code is pointing at player 1 for both ships!

Very strange, ships are registered in `driver.lua` on their first `update` call using `modkit.compose:instantiate`, which passes through the player ID param the normal custom code hooks receive. This should then index the `GLOBAL_PLAYERS` table. You could check the contents of that table perhaps? On both the custom code and rules code sides maybe.

---

Aside about the hoister:

The way it's working is that the ship is sent through a [hypertable](https://github.com/Novaras/modkit/blob/master/scripts/modkit/hypertable.lua) from the custom code scope, into the mission rules scope. We store the type and player index, and parse these on the other side.

You can see `GLOBAL_SHIPS` is being written to in that file, which is strange because we should already have this ship in ` GLOBAL_SHIPS`, however, the `create` and `update` hooks for custom code run in a different scope to the mission rules, so if we do

```lua
-- in custom code

GLOBAL_SHIPS:set(some_id, ship_def);
```

we will get nothing when trying to access it in the rules scope:

```
-- my_mission_script.lua

GLOBAL_SHIPS:get(the_same_id); -- nil
```

so thats why we are sending the data through the hypertable and syncing it over on the rules side.

**Comment by Novaras** [comment]
The fact that `SobGroup_GetPlayerOwner(self.own_group)` is returning the same value actually might mean that the `own_group`s are somehow becoming the same, or the player was switched. If you can see the player wasn't switched, then somehow the groups are becoming the same group 🤔

**Comment by Novaras** [comment]
Pushed an update which fixes a crash in `create` hook, may help.

**Comment by GeoffWilkinson** [comment]
> Pushed an update which fixes a crash in `create` hook, may help.

This didn't affect the behaviour (I did notice the error complaining about `create` not existing went away though)

> The fact that SobGroup_GetPlayerOwner(self.own_group) is returning the same value actually might mean that the own_groups are somehow becoming the same, or the player was switched. If you can see the player wasn't switched, then somehow the groups are becoming the same group 🤔

This looks to be the case! Kind of... I added `SobGroup_Count()` to my debug logging:

Pre first hoist:
```
------------------------------------------------------------------------------------
self.id: 16
self.player.id: 0
self.own_group: my_test_ship-16
SobGroup_GetPlayerOwner(self.own_group): 0
SobGroup_Count(self.own_group): 1
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
self.id: 384
self.player.id: 1
self.own_group: my_test_ship-384
SobGroup_GetPlayerOwner(self.own_group): 1
SobGroup_Count(self.own_group): 1
------------------------------------------------------------------------------------
```
Hoist + printing table:
```
[6.000004768371582] HOISTING GROUPS... -- Line 42 modkit-hoist-memgroups.lua in modkit_hoist_memgroups()
no ship matched, hoisting ship 384 -- Line 155 driver.lua in register()
no ship matched, hoisting ship 16 -- Line 155 driver.lua in register()
"table: 325814A0": {
        "384": {
                "group": "my_test_ship-384",
                "player": 1,
                "id": 384,

                "type": "my_test_ship",
        },
        "16": {
                "group": "my_test_ship-16",
                "player": 0,
                "id": 16,
                "type": "my_test_ship",
        },
}, -- Lines 72 -> 80 modkit-hoist-memgroups.lua in modkit_hoist_memgroups()
```
Now this is where it gets interesting...
```
------------------------------------------------------------------------------------
self.id: 16
self.player.id: 1
self.own_group: my_test_ship-16
SobGroup_GetPlayerOwner(self.own_group): 1
SobGroup_Count(self.own_group): 2
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
self.id: 384
self.player.id: 1
self.own_group: my_test_ship-384
SobGroup_GetPlayerOwner(self.own_group): 1
SobGroup_Count(self.own_group): 1
------------------------------------------------------------------------------------
```
So the sobgroup with the ship ID 16 (player 0 previously) now has two ships inside! The sobgroup with ship ID 384 still has just one ship. So it looks like `my_test_ship-16` gets the ship from player 1 added to it but it isn't reciprocated.

**Comment by GeoffWilkinson** [comment]
I've isolated the change in sobgroup player owner to somewhere in this block in `copse:instantiate` in `compose.lua`:

```lua
		local instance = modkit.table.reduce(
			source,
			function (acc, proto)
				local attribs = proto.attribs;
				local result = {};
				if (attribs) then
					if (type(attribs) == "function") then
						result = attribs(%sobgroup, %player_index, %id, %ship_type);
					end
				end

				return modkit.table:merge(acc, result);
			end,
			{}
		);
```

When setting attribs, the sobgroup of the ship type (`my_test_ship`) is cloned to the specific ship's sobgroup (`my_test_ship-16`). The sobgroup for the ship type is already `1` at this point for some reason.

**Comment by GeoffWilkinson** [comment]
/It looks like the issue is that in the local scope, e.g. inside a ships' `update` function the ship type sobgroup `my_test_ship` would be owned by player 0 in ship 16's case and player 1 in ship 384's case BUT in `register` it was always player 1 and seemed to be globally defined, so I think a fix is performing the cloning of the ship type sobgroup while still in local scope by doing
```lua
local new_ship = register(SobGroup_Clone(type_group, type_group .. player_index), player_index, ship_id);
```
in `modkit_hoist_memgroups()` - `modkit-hoist-memgroups.lua line 65`

I'm not fully confident in this as a fix as it feels hacky and I'm not sure why it works but using more complex logging I get:

```
------------------------------------------------------------------------------------
self.id: 16
self.player.id: 0
self.own_group: my_test_ship-16
self.type_group: my_test_ship
self.ship_type: my_test_ship
SobGroup_GetPlayerOwner(self.own_group): 0
SobGroup_GetPlayerOwner(self.type_group): 0
SobGroup_GetPlayerOwner(self.ship_type): 0
SobGroup_Count(self.own_group): 1
SobGroup_Count(self.type_group): 1
SobGroup_Count(self.ship_type): 1
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
self.id: 384
self.player.id: 1
self.own_group: my_test_ship-384
self.type_group: my_test_ship
self.ship_type: my_test_ship
SobGroup_GetPlayerOwner(self.own_group): 1
SobGroup_GetPlayerOwner(self.type_group): 1
SobGroup_GetPlayerOwner(self.ship_type): 1
SobGroup_Count(self.own_group): 1
SobGroup_Count(self.type_group): 1
SobGroup_Count(self.ship_type): 1
------------------------------------------------------------------------------------
```
in every update tick from game start to post hoist!

**Comment by Novaras** [comment]
Very weird, I think the issue is the call to `SobGroup_Clone` in `modkit-base.lua`, which is being called twice with the same group name due to the two calls to `register`; that is, sobgroups exist in all scopes but the tables and Lua data we're working with are limited to thier scopes.

I'm still investigating the root cause, but I have pushed a fix which simply checks if the group is populated before adding (in driver, update).

Could you try now?

**Comment by GeoffWilkinson** [comment]
Still getting the same issue, after the hoist, ships of the same type but different teams still land in the same "team". This is doing a mirror between 2 Hiigarans (I added a script to the `hgn_carrier`):

```
------------------------------------------------------------------------------------
self.id: 16
self.player.id: 0
self.own_group: hgn_carrier-16
SobGroup_GetPlayerOwner(self.own_group): 0
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
self.id: 128
self.player.id: 1
self.own_group: hgn_carrier-128
SobGroup_GetPlayerOwner(self.own_group): 1
------------------------------------------------------------------------------------
[6.000004768371582] HOISTING GROUPS...

------------------------------------------------------------------------------------
self.id: 16
self.player.id: 1
self.own_group: hgn_carrier-16
SobGroup_GetPlayerOwner(self.own_group): 1
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
self.id: 128
self.player.id: 1
self.own_group: hgn_carrier-128
SobGroup_GetPlayerOwner(self.own_group): 1
------------------------------------------------------------------------------------
```

**Comment by Novaras** [comment]
Could it be due to difference indexing the player IDs on each side? This is truly bizarre..

For now I'd say, just comment out the call to hoist: unless what you're doing requires ship access on gamerule and custom code both, it won't matter if hoist doesn't run
